# docker-compose.yaml
version: "3"
services:
    web:
      build:
        context: .
        dockerfile: Dockerfile-node
      ports:
        - "8081:8080"
      volumes:
        - "./server:/usr/src/app"
      depends_on:
        - mongo
    mongo:
        image: "mongo:4.2.5"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        volumes:
            - "./mongo:/docker-entrypoint-initdb.d"
